### ISSUE TITLE
Codegen issues in rand crate

### ISSUE THREAD

**Issue by nchong-at-aws** [model-checking/rmc#111] opened 2021-05-04 14:51 UTC
Trying to compile `rand` crate:

```bash
git clone https://github.com/rust-random/rand.git
cd rand
RUST_BACKTRACE=1 RUSTFLAGS="-Z trim-diagnostic-paths=no -Z codegen-backend=gotoc" RUSTC_LOG="rustc_codegen_llvm::gotoc" RUSTC=rmc-rustc cargo build --verbose --target x86_64-unknown-linux-gnu -j 1 
```

crashes RMC:

```
thread 'rustc' panicked at 'Can't cast

Expr { value: Symbol { identifier: "_ZN80_$LT$dyn$u20$std..error..Error$u2b$core..marker..Send$u2b$core..marker..Sync$GT$12downcast_ref17h06378e08c6fa74f7E::1::var_3" }, typ: StructTag("tag-dyn std::error::Error + core::marker::Send + core::marker::Sync"), location: None }

Pointer { typ: Empty }', compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/expr.rs:409:9
stack backtrace:
   0: rust_begin_unwind
             at /local/home/ncchong/rmc/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /local/home/ncchong/rmc/library/std/src/panicking.rs:435:5
   2: rustc_codegen_llvm::gotoc::cbmc::goto_program::expr::Expr::cast_to
             at /local/home/ncchong/rmc/compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/expr.rs:409:9
   3: rustc_codegen_llvm::gotoc::rvalue::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::cast_sized_pointer_to_trait_fat_pointer
             at /local/home/ncchong/rmc/compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:962:33
   4: rustc_codegen_llvm::gotoc::rvalue::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::cast_sized_pointer_to_fat_pointer
             at /local/home/ncchong/rmc/compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:907:13
   5: rustc_codegen_llvm::gotoc::rvalue::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::cast_sized_expr_to_unsized_expr
   6: rustc_codegen_llvm::gotoc::rvalue::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_pointer_cast
             at /local/home/ncchong/rmc/compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:653:37
   7: rustc_codegen_llvm::gotoc::rvalue::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_rvalue
             at /local/home/ncchong/rmc/compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:384:17
   8: rustc_codegen_llvm::gotoc::statement::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_statement
             at /local/home/ncchong/rmc/compiler/rustc_codegen_llvm/src/gotoc/statement.rs:412:60
   9: rustc_codegen_llvm::gotoc::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_block
             at /local/home/ncchong/rmc/compiler/rustc_codegen_llvm/src/gotoc/mod.rs:59:32
  10: rustc_codegen_llvm::gotoc::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_function::{{closure}}
             at /local/home/ncchong/rmc/compiler/rustc_codegen_llvm/src/gotoc/mod.rs:113:71
  11: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /local/home/ncchong/rmc/library/core/src/iter/traits/iterator.rs:773:29
  12: core::iter::adapters::map::map_fold::{{closure}}
             at /local/home/ncchong/rmc/library/core/src/iter/adapters/map.rs:82:21
  13: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::enumerate::{{closure}}
             at /local/home/ncchong/rmc/library/core/src/iter/adapters/enumerate.rs:104:27
  14: core::iter::traits::iterator::Iterator::fold
             at /local/home/ncchong/rmc/library/core/src/iter/traits/iterator.rs:2147:21
  15: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold
             at /local/home/ncchong/rmc/library/core/src/iter/adapters/enumerate.rs:110:9
  16: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /local/home/ncchong/rmc/library/core/src/iter/adapters/map.rs:122:9
  17: core::iter::traits::iterator::Iterator::for_each
             at /local/home/ncchong/rmc/library/core/src/iter/traits/iterator.rs:776:9
  18: rustc_codegen_llvm::gotoc::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_function
             at /local/home/ncchong/rmc/compiler/rustc_codegen_llvm/src/gotoc/mod.rs:113:13
  19: <rustc_codegen_llvm::gotoc::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
             at /local/home/ncchong/rmc/compiler/rustc_codegen_llvm/src/gotoc/mod.rs:281:47
  20: rustc_interface::passes::start_codegen::{{closure}}
             at /local/home/ncchong/rmc/compiler/rustc_interface/src/passes.rs:1021:9
  21: rustc_data_structures::profiling::VerboseTimingGuard::run
             at /local/home/ncchong/rmc/compiler/rustc_data_structures/src/profiling.rs:573:9
  22: rustc_session::utils::<impl rustc_session::session::Session>::time
             at /local/home/ncchong/rmc/compiler/rustc_session/src/utils.rs:16:9
  23: rustc_interface::passes::start_codegen
             at /local/home/ncchong/rmc/compiler/rustc_interface/src/passes.rs:1020:19
  24: rustc_interface::queries::Queries::ongoing_codegen::{{closure}}::{{closure}}
             at /local/home/ncchong/rmc/compiler/rustc_interface/src/queries.rs:296:20
  25: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /local/home/ncchong/rmc/compiler/rustc_interface/src/passes.rs:755:42
  26: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /local/home/ncchong/rmc/compiler/rustc_middle/src/ty/context.rs:1733:50
  27: rustc_middle::ty::context::tls::set_tlv
             at /local/home/ncchong/rmc/compiler/rustc_middle/src/ty/context.rs:1717:9
  28: rustc_middle::ty::context::tls::enter_context
             at /local/home/ncchong/rmc/compiler/rustc_middle/src/ty/context.rs:1733:9
  29: rustc_interface::passes::QueryContext::enter
             at /local/home/ncchong/rmc/compiler/rustc_interface/src/passes.rs:755:9
  30: rustc_interface::queries::Queries::ongoing_codegen::{{closure}}
             at /local/home/ncchong/rmc/compiler/rustc_interface/src/queries.rs:287:13
  31: rustc_interface::queries::Query<T>::compute
             at /local/home/ncchong/rmc/compiler/rustc_interface/src/queries.rs:40:28
  32: rustc_interface::queries::Queries::ongoing_codegen
             at /local/home/ncchong/rmc/compiler/rustc_interface/src/queries.rs:285:9
  33: rustc_driver::run_compiler::{{closure}}::{{closure}}
             at /local/home/ncchong/rmc/compiler/rustc_driver/src/lib.rs:442:13
  34: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
             at /local/home/ncchong/rmc/compiler/rustc_interface/src/queries.rs:432:19
  35: rustc_driver::run_compiler::{{closure}}
             at /local/home/ncchong/rmc/compiler/rustc_driver/src/lib.rs:337:22
  36: rustc_interface::interface::create_compiler_and_run::{{closure}}
             at /local/home/ncchong/rmc/compiler/rustc_interface/src/interface.rs:208:13
  37: rustc_span::with_source_map
             at /local/home/ncchong/rmc/compiler/rustc_span/src/lib.rs:787:5
  38: rustc_interface::interface::create_compiler_and_run
             at /local/home/ncchong/rmc/compiler/rustc_interface/src/interface.rs:202:5
  39: rustc_interface::interface::run_compiler::{{closure}}
             at /local/home/ncchong/rmc/compiler/rustc_interface/src/interface.rs:224:12
  40: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}::{{closure}}
             at /local/home/ncchong/rmc/compiler/rustc_interface/src/util.rs:155:13
  41: scoped_tls::ScopedKey<T>::set
             at /home/ncchong/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  42: rustc_span::with_session_globals
             at /local/home/ncchong/rmc/compiler/rustc_span/src/lib.rs:104:5
  43: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}
             at /local/home/ncchong/rmc/compiler/rustc_interface/src/util.rs:153:9
  44: rustc_interface::util::scoped_thread::{{closure}}
             at /local/home/ncchong/rmc/compiler/rustc_interface/src/util.rs:128:24
```

**Comment by adpaco-aws** [comment] 2021-06-17 17:02
Just confirmed that this is failing again due to the `Can't cast ...` error posted originally.

**Comment by avanhatt** [comment] 2021-06-22 15:10
#203 does help us get further into compiling this crate, but unfortunately, even with more fixes we eventually hit this:

```rust
thread 'rustc' panicked at 'not implemented: unsupported intrinsic: simd_shuffle8
```

**Comment by adpaco-aws** [comment] 2021-06-22 15:19
That is great, I can take it from there.

**Comment by adpaco-aws** [comment] 2021-07-08 17:17
Actually, I'm getting a panic due to another SIMD intrinsic with most recent version of RMC:
```
thread 'rustc' panicked at 'not implemented: unsupported intrinsic: simd_insert
```

Opening an issue for each one.

**Comment by adpaco-aws** [comment] 2021-08-23 14:50
Trying again after #417 got merged brings up another error (trace below). It is similar to #412 (codegen `regex` crate).

```
thread 'rustc' panicked at 'assertion failed: current_offset <= next_offset', compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/typ.rs:556:9
stack backtrace:
   0: rust_begin_unwind
             at /home/ubuntu/rmc-rand/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /home/ubuntu/rmc-rand/library/core/src/panicking.rs:93:14
   2: core::panicking::panic
             at /home/ubuntu/rmc-rand/library/core/src/panicking.rs:50:5
   3: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::typ::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_struct_padding
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/typ.rs:556:9
   4: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::typ::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_struct_fields
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/typ.rs:605:25
   5: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::typ::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_variant_struct_fields
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/typ.rs:854:9
   6: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::typ::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_enum_case_struct::{{closure}}
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/typ.rs:1089:13
   7: rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx::ensure_struct
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/context/goto_ctx.rs:169:30
   8: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::typ::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_enum_case_struct
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/typ.rs:1088:9
   9: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::typ::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_enum_cases_union::{{closure}}::{{closure}}
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/typ.rs:1065:25
  10: core::iter::adapters::map::map_fold::{{closure}}
             at /home/ubuntu/rmc-rand/library/core/src/iter/adapters/map.rs:84:28
  11: core::iter::adapters::map::map_fold::{{closure}}
             at /home/ubuntu/rmc-rand/library/core/src/iter/adapters/map.rs:84:21
  12: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::enumerate::{{closure}}
             at /home/ubuntu/rmc-rand/library/core/src/iter/adapters/enumerate.rs:106:27
  13: core::iter::traits::iterator::Iterator::fold
             at /home/ubuntu/rmc-rand/library/core/src/iter/traits/iterator.rs:2170:21
  14: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold
             at /home/ubuntu/rmc-rand/library/core/src/iter/adapters/enumerate.rs:112:9
  15: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /home/ubuntu/rmc-rand/library/core/src/iter/adapters/map.rs:124:9
  16: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /home/ubuntu/rmc-rand/library/core/src/iter/adapters/map.rs:124:9
  17: core::iter::traits::iterator::Iterator::for_each
             at /home/ubuntu/rmc-rand/library/core/src/iter/traits/iterator.rs:733:9
  18: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /home/ubuntu/rmc-rand/library/alloc/src/vec/spec_extend.rs:40:17
  19: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /home/ubuntu/rmc-rand/library/alloc/src/vec/spec_from_iter_nested.rs:56:9
  20: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /home/ubuntu/rmc-rand/library/alloc/src/vec/spec_from_iter.rs:33:9
  21: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /home/ubuntu/rmc-rand/library/alloc/src/vec/mod.rs:2485:9
  22: core::iter::traits::iterator::Iterator::collect
             at /home/ubuntu/rmc-rand/library/core/src/iter/traits/iterator.rs:1745:9
  23: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::typ::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_enum_cases_union::{{closure}}
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/typ.rs:1060:13
  24: rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx::ensure_union
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/context/goto_ctx.rs:188:30
  25: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::typ::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_enum_cases_union
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/typ.rs:1059:9
  26: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::typ::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_enum::{{closure}}
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/typ.rs:951:33
  27: rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx::ensure_struct
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/context/goto_ctx.rs:169:30
  28: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::typ::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_enum
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/typ.rs:916:9
  29: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::typ::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_ty
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/typ.rs:444:21
  30: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::typ::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_ty_ref
  31: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::typ::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_ty
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/typ.rs:474:76
  32: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::typ::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_ty_ref
  33: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::typ::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_ty
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/typ.rs:474:76
  34: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::typ::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::fn_typ::{{closure}}
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/typ.rs:1136:80
  35: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /home/ubuntu/rmc-rand/library/core/src/ops/function.rs:269:13
  36: core::iter::traits::iterator::Iterator::find_map::check::{{closure}}
             at /home/ubuntu/rmc-rand/library/core/src/iter/traits/iterator.rs:2407:32
  37: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::try_fold::enumerate::{{closure}}
             at /home/ubuntu/rmc-rand/library/core/src/iter/adapters/enumerate.rs:85:27
  38: core::iter::traits::iterator::Iterator::try_fold
             at /home/ubuntu/rmc-rand/library/core/src/iter/traits/iterator.rs:1994:21
  39: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::try_fold
             at /home/ubuntu/rmc-rand/library/core/src/iter/adapters/enumerate.rs:91:9
  40: core::iter::traits::iterator::Iterator::find_map
             at /home/ubuntu/rmc-rand/library/core/src/iter/traits/iterator.rs:2413:9
  41: <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
             at /home/ubuntu/rmc-rand/library/core/src/iter/adapters/filter_map.rs:61:9
  42: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /home/ubuntu/rmc-rand/library/alloc/src/vec/spec_from_iter_nested.rs:23:32
  43: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /home/ubuntu/rmc-rand/library/alloc/src/vec/spec_from_iter.rs:33:9
  44: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /home/ubuntu/rmc-rand/library/alloc/src/vec/mod.rs:2485:9
  45: core::iter::traits::iterator::Iterator::collect
             at /home/ubuntu/rmc-rand/library/core/src/iter/traits/iterator.rs:1745:9
  46: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::typ::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::fn_typ
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/typ.rs:1114:42
  47: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::function::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::declare_function::{{closure}}
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/function.rs:194:17
  48: rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx::ensure
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/context/goto_ctx.rs:127:23
  49: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::function::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::declare_function
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/function.rs:190:9
  50: <rustc_codegen_llvm::gotoc::mir_to_goto::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{{closure}}
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/compiler_interface.rs:70:35
  51: rustc_codegen_llvm::gotoc::mir_to_goto::utils::debug::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::call_with_panic_debug_info::{{closure}}
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/utils/debug.rs:77:13
  52: std::thread::local::LocalKey<T>::try_with
             at /home/ubuntu/rmc-rand/library/std/src/thread/local.rs:399:16
  53: std::thread::local::LocalKey<T>::with
             at /home/ubuntu/rmc-rand/library/std/src/thread/local.rs:375:9
  54: rustc_codegen_llvm::gotoc::mir_to_goto::utils::debug::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::call_with_panic_debug_info
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/utils/debug.rs:75:9
  55: <rustc_codegen_llvm::gotoc::mir_to_goto::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
             at /home/ubuntu/rmc-rand/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/compiler_interface.rs:69:25
  56: rustc_interface::passes::start_codegen::{{closure}}
             at /home/ubuntu/rmc-rand/compiler/rustc_interface/src/passes.rs:1053:9
  57: rustc_data_structures::profiling::VerboseTimingGuard::run
             at /home/ubuntu/rmc-rand/compiler/rustc_data_structures/src/profiling.rs:611:9
  58: rustc_session::utils::<impl rustc_session::session::Session>::time
             at /home/ubuntu/rmc-rand/compiler/rustc_session/src/utils.rs:16:9
  59: rustc_interface::passes::start_codegen
             at /home/ubuntu/rmc-rand/compiler/rustc_interface/src/passes.rs:1052:19
  60: rustc_interface::queries::Queries::ongoing_codegen::{{closure}}::{{closure}}
             at /home/ubuntu/rmc-rand/compiler/rustc_interface/src/queries.rs:254:20
  61: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /home/ubuntu/rmc-rand/compiler/rustc_interface/src/passes.rs:779:42
  62: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /home/ubuntu/rmc-rand/compiler/rustc_middle/src/ty/context.rs:1782:50
  63: rustc_middle::ty::context::tls::set_tlv
             at /home/ubuntu/rmc-rand/compiler/rustc_middle/src/ty/context.rs:1766:9
  64: rustc_middle::ty::context::tls::enter_context
             at /home/ubuntu/rmc-rand/compiler/rustc_middle/src/ty/context.rs:1782:9
  65: rustc_interface::passes::QueryContext::enter
             at /home/ubuntu/rmc-rand/compiler/rustc_interface/src/passes.rs:779:9
  66: rustc_interface::queries::Queries::ongoing_codegen::{{closure}}
             at /home/ubuntu/rmc-rand/compiler/rustc_interface/src/queries.rs:245:13
  67: rustc_interface::queries::Query<T>::compute
             at /home/ubuntu/rmc-rand/compiler/rustc_interface/src/queries.rs:38:28
  68: rustc_interface::queries::Queries::ongoing_codegen
             at /home/ubuntu/rmc-rand/compiler/rustc_interface/src/queries.rs:243:9
  69: rustc_driver::run_compiler::{{closure}}::{{closure}}
             at /home/ubuntu/rmc-rand/compiler/rustc_driver/src/lib.rs:407:13
  70: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
             at /home/ubuntu/rmc-rand/compiler/rustc_interface/src/queries.rs:394:19
  71: rustc_driver::run_compiler::{{closure}}
             at /home/ubuntu/rmc-rand/compiler/rustc_driver/src/lib.rs:312:22
  72: rustc_interface::interface::create_compiler_and_run::{{closure}}
             at /home/ubuntu/rmc-rand/compiler/rustc_interface/src/interface.rs:209:13
  73: rustc_span::with_source_map
             at /home/ubuntu/rmc-rand/compiler/rustc_span/src/lib.rs:911:5
  74: rustc_interface::interface::create_compiler_and_run
             at /home/ubuntu/rmc-rand/compiler/rustc_interface/src/interface.rs:203:5
  75: rustc_interface::interface::run_compiler::{{closure}}
             at /home/ubuntu/rmc-rand/compiler/rustc_interface/src/interface.rs:225:12
  76: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}::{{closure}}
             at /home/ubuntu/rmc-rand/compiler/rustc_interface/src/util.rs:157:13
  77: scoped_tls::ScopedKey<T>::set
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  78: rustc_span::create_session_globals_then
             at /home/ubuntu/rmc-rand/compiler/rustc_span/src/lib.rs:105:5
  79: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}
             at /home/ubuntu/rmc-rand/compiler/rustc_interface/src/util.rs:155:9
  80: rustc_interface::util::scoped_thread::{{closure}}
             at /home/ubuntu/rmc-rand/compiler/rustc_interface/src/util.rs:130:24
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z trim-diagnostic-paths=no -Z codegen-backend=gotoc -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack

[RMC] current codegen item: declare_function: <&T as core::fmt::Debug>::fmt

RMC unexpectedly panicked during code generation.

If you are seeing this message, please file an issue here instead of on the Rust compiler: https://github.com/model-checking/rmc/issues/new?labels=bug&template=bug_report.md
error: could not compile `rand`
```

**Closed** 2021-09-03 02:43 UTC
Labels: bug
